apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-web
  labels:
    app: real-estate-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-estate-web
  template:
    metadata:
      labels:
        app: real-estate-web
    spec:
      containers:
        - name: app
          image: ghcr.io/andrew-all-proj/real-estate-web:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3009
      imagePullSecrets:
        - name: real-estate-web
