apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-estate-web-ingress
  namespace: real-estate
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  rules:
    - host: test.managetlg.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-estate-web
                port:
                  number: 80
  tls:
    - hosts:
        - test.managetlg.com
