apiVersion: v1
kind: Service
metadata:
  name: real-estate-web
  namespace: real-estate
  labels:
    app: real-estate-web
spec:
  selector:
    app: real-estate-web
  ports:
    - name: http
      port: 80
      targetPort: 3009
